export const FORBIDDEN_WORDS = [
  // DIVERSOS
  'DIVERSOS', 'DIV', 'DIVERSA',
  'OUTROS', 'OUTRO', 'OUTR',
  'VARIADOS', 'VARIEDADE',
  'MISC', 'MISCELÂNEA', 'MISCELANEA',
  'ETC', 'ETCETERA',
  'PRODUTO', 'PROD',
  'ITEM', 'ITENS',
  'MERCADORIA',

  // TESTE / CADASTRO
  'TESTE', 'TESTANDO',
  'CADASTRO', 'CADASTRAR',
  'NOVO', 'NOVO ITEM',
  'XXX', 'ZZZ',

  // CORREÇÃO / SISTEMA
  'AJUSTE',
  'ERRO',
  'CORREÇÃO', 'CORRECAO',
  'VALOR', 'PREÇO', 'PRECO',
  'AVULSO', 'AVULSA',
  'GENERICO', 'GENERICA', 'GENÉRICO', 'GENÉRICA',
  'PADRÃO', 'PADRAO',
  'SISTEMA',
  'NOME', 'SEM NOME',

  // CATEGORIAS VAGAS
  'BEBIDA',
  'DRINK', 'DRINQUE',
  'COQUETEL',
  'COMIDA', 'RANGO', 'PETISCO',
  'COISA',
  'ALCOÓLICO', 'ALCOOLICO', 'NÃO ALCOÓLICO', 'NAO ALCOOLICO',
  'IMPORTADO', 'NACIONAL',
  'COZINHA', 'BALCÃO', 'BALCAO', 'BAR'
];

export const KEYBOARD_SEQUENCES = [
  'ASDF', 'QWERTY', '123'
];

export const REPETITIVE_NUMBERS = [
  '000', '111', '222', '333', '444', '555', '666', '777', '888', '999'
];
